### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by pertrai1** [ericelliott/essential-javascript-links#18]
I might be a little late to the party in regards to where this will be hosted, but can't this be created using Jekyll and be a github page? I am not an expert in using Jekyll, but the one time I did create a github io using Jekyll, I thought it was straight forward. 

If any of this has already been decided, I apologize for bringing this up.

Rob

**Comment by ericelliott** [comment]
Hi Rob,

There are some dynamic features planned that wouldn't work with Jekyll / GH Pages.

**Comment by pertrai1** [comment]
Sounds great. Will look over the code base and see if I can be of any help.

Rob
