### ISSUE TITLE
Remove /build from the git repo?

### ISSUE THREAD

**Issue by Nicholas-Perry** [ericelliott/essential-javascript-links#21]
Not sure if this is intentional, but it seems the readme file is duplicated under the build directory, however it does not seem to have the latest changes compared to the one in the root.

**Comment by ericelliott** [comment]
Yeah, we should probably not check `/build` into the repo...

**Comment by ericelliott** [comment]
I don't feel strongly about this. If you're interested, please feel free to open a PR.
