### ISSUE TITLE
Add http://javascriptkicks.com & http://twitter.com/javascriptkicks

### ISSUE THREAD

**Issue by jordonbaade** [ericelliott/essential-javascript-links#26]
Love the list of resources here!

Can we get http://javascriptkicks.com added to the News section and http://twitter.com/javascriptkicks added to Twitter?

Thanks :)

**Comment by ericelliott** [comment]
Sounds good. PR?

**Comment by jordonbaade** [comment]
Sure thing Eric, here you go: #27

**Comment by ericelliott** [comment]
Thanks!
