### ISSUE TITLE
javascript-sdk-design

### ISSUE THREAD

**Issue by huei90** [ericelliott/essential-javascript-links#29]
Can I add [javascript-sdk-design](https://github.com/huei90/javascript-sdk-design) into the list?

It belongs to which part?

Thanks.

BTW, great links :smile:

**Comment by ericelliott** [comment]
Cool. =)

There's a [whole book on this topic](http://thirdpartyjs.com/). Have you seen it?

**Comment by huei90** [comment]
Yes, I have included the book link 
https://github.com/huei90/javascript-sdk-design#booknice-to-read

**Comment by ericelliott** [comment]
Are you aware of [`lightning.js`](https://github.com/olark/lightningjs)?

**Comment by huei90** [comment]
Cool! Thanks @ericelliott 
I don't know anything about this yet!
Seems it's nice to read and learn!

**Comment by ericelliott** [comment]
:+1: You did a good job hitting most of the essentials of browser SDK design. Thanks. =)

**Comment by huei90** [comment]
Thanks, but I think there is still many to improve
grammar sentence used, title clarify, more essential content and more design suggestion.
