### ISSUE TITLE
Book and Tutorial additions

### ISSUE THREAD

**Issue by Cryptolemming** [ericelliott/essential-javascript-links#36]
Book (React +):
http://survivejs.com/

Tutorial (React +)
http://sahatyalkabov.com/create-a-character-voting-app-using-react-nodejs-mongodb-and-socketio/

Great list! :)

**Comment by ericelliott** [comment]
Thanks for your feedback and suggestions. =)

Re: SurviveJS - I am not adding any new resources which teach `class`. See [How to Build a High Velocity Development Team](https://medium.com/javascript-scene/how-to-build-a-high-velocity-development-team-4b2360d34021#0147).

Voting app: I'm not adding any new resources written in ES5. It could confuse new JavaScript users who learned in ES6. That's not a huge problem right now, today, but it will be this time next year.
