### ISSUE TITLE
[Please Review] Event Loop Visualization

### ISSUE THREAD

**Issue by MarcCloud** [ericelliott/essential-javascript-links#38]
I have found this app and video very useful to explain people new to JavaScript what is and how does work the event loop and the asynchronous functions. 

[LoupeJS](http://latentflip.com/loupe/)   #experience #long_video

**Comment by ericelliott** [comment]
Thanks. It's cool... definitely worthy of a tweet, but I don't think it qualifies as an essential resource. =)
