### ISSUE TITLE
New JavaScript Environment?

### ISSUE THREAD

**Issue by chad-autry** [ericelliott/essential-javascript-links#39]
Recent infoq article brought JerryScript to my attention. http://www.infoq.com/news/2015/08/iotjs-jerryscript-samsung

I believe a link under the JavaScript Environments section would not be amiss.

**Comment by ericelliott** [comment]
Added the IoT.js homepage. https://github.com/ericelliott/essential-javascript-links/commit/320d7568e4d4863fce61c560acbea60cca1e271c
