### ISSUE TITLE
Code School's JavaScript Resources

### ISSUE THREAD

**Issue by nrcs** [ericelliott/essential-javascript-links#40]
Hey Eric, 

My name is Nick and I'm part of the team at Code School (codeschool.com) - maybe you've heard of us? 

I just came across your Essential JavaScript Links and wanted to know if you'd ever checked out Code School's JavaScript courses (https://www.codeschool.com/paths/javascript) or JavaScript podcasts (fivejs.codeschool.com)? Our course library offers some free courses on things like Angular and jQuery and our FiveJS podcast covers weekly JS news/frameworks/projects in under five minutes. We also recently launched javascript.com, an independent and free community resource for JavaScript news and resources.

Let me know if you'd like a membership to check out Code School's course library and I'd be happy to send you a membership. 

Thanks Eric.

**Comment by Dan-Ste** [comment]
I'm not Eric...

2015-08-07 18:22 GMT+03:00 nrcs <notifications@github.com>:

**Comment by nrcs** [comment]
Sorry about that Dan. The EJL said to submit an issue to suggest resources for the list, so I apologize! Would it be better to reach out to Eric via email?

**Comment by Dan-Ste** [comment]
I don't even know Eric, but yes, I heard of you. Nice courses on your
website. I walked a few, but unfortunately only free)

2015-08-07 18:27 GMT+03:00 nrcs <notifications@github.com>:

**Comment by ericelliott** [comment]
Dan,

Is it possible you're following the project, so you get email notifications when somebody submits a new issue? I believe you can turn that off if you don't want to get emails. =)

Nick,

We're very picky about the resources we link to here. I think there's probably a bit too much overlap between your free courses and learning resources we already link to. If you have specific courses to recommend, that may be a better approach.

**Comment by Dan-Ste** [comment]
Your courses are much better than the other free. But now I can not afford
to use them. But if you want to know what resources I use now, here they
are - https://www.codecademy.com/ http://www.theodinproject.com/. I also
use to study literature from OReylli and some Russian-language resources,
but I think it's not interesting for you))
And I unsubscribe. Thanks. I don't remember when I signed up for email
notifications.

2015-08-08 3:34 GMT+03:00 Eric Elliott <notifications@github.com>:

**Comment by nrcs** [comment]
Hey Eric, 

Thanks for the reply. I'd recommend checking out our Angular course (https://www.codeschool.com/courses/shaping-up-with-angular-js) and for dev tools, our Try Git course helps introduce Git to new developers (try.github.io/).

We're also working to expand the community news section of https://www.javascript.com/ to be a great place to go to keep up to date with community news and jump into learning JavaScript if you're not familiar with the basics. 

Thanks Eric. Regardless, I'll be bookmarking the list to share around.

**Comment by ericelliott** [comment]
* [x] News link added.
* [x] Try Git added to [JSHomes Learning Resources](https://github.com/jshomes/learning-resources/blob/master/tracks/dev-tools/git-and-github/index.md) (to be used for many job training programs).

**Comment by nrcs** [comment]
Thanks Eric!
