### ISSUE TITLE
JS libraries

### ISSUE THREAD

**Issue by Pugi** [ericelliott/essential-javascript-links#43]
Hi Eric,

Dojo Toolkit (http://dojotoolkit.org/) is a good candidate as a JS library.

Bogdan

**Comment by ericelliott** [comment]
Thanks. Do you  have some favorite modules?

**Comment by Pugi** [comment]
EnhancedGrid (and now Gridx) is the one I use most.

**Comment by ericelliott** [comment]
These are too mired in classical inheritance for my taste.
