### ISSUE TITLE
Shall I put the libraries under categories. The list is getting long

### ISSUE THREAD

**Issue by aladdine** [ericelliott/essential-javascript-links#48]
Suggested categories: DOM Manipulation, Security, Cookie handling, Testing, Events Handling, Ajax, Animation and graphics, Visualizations, Functional programming, Other. @ericelliott

**Comment by ericelliott** [comment]
What categories would you suggest?

**Comment by moklick** [comment]
Maybe it would make more sense to link to a repo like [https://github.com/sorrycc/awesome-javascript](awesome javascript) for example, in contrast to collect all the libs here again.

**Comment by ericelliott** [comment]
@moklick That would be missing the point of curation.

@aladdine I'm happy to consider this. Open a PR or post some suggested categories to make it happen.
