### ISSUE TITLE
[Please review]

### ISSUE THREAD

**Issue by nankathi** [ericelliott/essential-javascript-links#50]
Please have a look at this video series for JS 
https://www.youtube.com/watch?v=PMsVM7rjupU&list=PL6n9fhu94yhUA99nOsJkKXBqokT3MBK0b
 I believe hes one of the best instructor with over 140k youtube subscribers. I thought it might be helpful and can make its place into the list 
Happy coding

**Comment by ericelliott** [comment]
Lots of subscribers or no, those videos contain some bad information, and I definitely don't recommend them.
