### ISSUE TITLE
New section: Hands-on training

### ISSUE THREAD

**Issue by alexloi** [ericelliott/essential-javascript-links#51]
I think there it might be worth adding a new section "Hands-on training" or something similar for resources that allow interactive training. A good first resource would be the nodeschool tutorials, cli-based, you get your hands dirty and I use it to onboard junior devs in my team with great success.

I'm sure they're more out there and it doesnt really fit into the current sections?

**Comment by ericelliott** [comment]
PR? =)

**Comment by ericelliott** [comment]
Got it. Done. =)
