### ISSUE TITLE
Do you have a list for atom plugins?

### ISSUE THREAD

**Issue by vasco3** [ericelliott/essential-javascript-links#58]

**Comment by ericelliott** [comment]
Nope. I don't use many.

**Comment by benbrownlol** [comment]
Maybe just a link to [Eric's post on JavaScript tooling](https://medium.com/javascript-scene/must-see-javascript-dev-tools-that-put-other-dev-tools-to-shame-aca6d3e3d925#.h1652pn8s) and [the post you reference regarding atom packages](https://medium.com/@satya164/supercharged-javascript-development-in-atom-ea034e22eabc#.gcu76n1ka) would help?

**Comment by ericelliott** [comment]
There is already a good curated list for Atom plugins: [Awesome Atom](https://github.com/mehcode/awesome-atom). Check it out.
