### ISSUE TITLE
Book and tutorials

### ISSUE THREAD

**Issue by helenasilkina** [ericelliott/essential-javascript-links#59]
Hi Eric,

This is a good book about Javascript by Nicholas C. Zakas: "Professional JavaScript for Web Developers".

I wonder that isn't Angular in your list. 
You can add video tutorials from this site https://egghead.io/tags/free
for example, javascript, React, Angular, ECMAscript 6, Node, grunt 

By the way thanks for interesting javascript list :)

**Comment by ericelliott** [comment]
I am a big fan of Nicholas Zakas, but that particular book is intentionally not on the list.

Angular is also intentionally not on the list.

Egghead's videos are a mixed bag. Some (like the [Redux tutorial](https://egghead.io/series/getting-started-with-redux)) are very good. Others will lead developers down awkward paths.
