### ISSUE TITLE
[Please review] Monkberry - DOM template engine

### ISSUE THREAD

**Issue by elfet** [ericelliott/essential-javascript-links#66]
Hi,

I'm developer of new dom-based template engine for web: http://monkberry.js.org
I know there a lot of it. But i think my is very cool. Please, review it.

**Comment by ericelliott** [comment]
JavaScript has built-in templates now. Why do we need another DOM-based template engine?

**Comment by elfet** [comment]
@ericelliott by _JavaScript built-in templates_ do you mean this?
```js
node.innerHTML = `<div>${text}</div>`;
```
If so, this is very slow solution for modern web, because browser need to parse text into AST and only then start creating DOM nodes. It's really slow for big apps. Solution of this is to create DOM node via DOM Api:
```js
var div = document.createElement('div');
div.textContent = text;
node.appendChild(div);
```
That's what DOM-based templates do. Most popular of them is React, and we use it a lot. But it also slow (needs to keep 3(!) DOM tree), and it's about 40kB gzip! All article about React performance prescribe to shouldComponentUpdate should return false (and use DOM Api). 

We start looking for other DOM-based templates (it must be small size, fast, and not to be a "framework"), but some of them have strange syntax, other offer just node creation (this is can be achieved with JSX only). 

So in our company we decide to research and create our own DOM-based engine (it's was called temple-wat, monkberry it's second generation).  

For example this template:
```html
<div>
  <h1>{{ title }}</h1>
  <p>
    {{ text }}
  </p>
</div>
```
can be compiled on server to something like this:
```js
```

**Comment by ericelliott** [comment]
Does it employ a virtual DOM and conditionally render updates like React does? Also, have you published the source code for the benchmarks?

**Comment by ericelliott** [comment]
Why does it have its own syntax for conditionals, forEach, etc... why not simply use JavaScript expressions for that?

**Comment by elfet** [comment]
No, it's does not use virtual DOM (the main idea is to leave user decide what to update, if fact whole update of data in DOM does not trigger a lot of reflows and repaints). 
```js
var view = monkberry.render('template', data);
// ...
view.update({title});
```
Source code of benchmarks is here: https://github.com/monkberry/benchmark
This is very popular syntax (mustache, liquid, twig), also we want to separate template from business logic. 
Monkberry support JavaScript expression inside `{{ foo.baz(bar) }}` and `{% %}`. It also create SourceMaps for template (only React do this too, none of other DOM-engines does not).

**Comment by elfet** [comment]
@ericelliott ping

**Comment by ericelliott** [comment]
Looks interesting. I'll give this a deeper look later. =)

**Comment by JACKMESON** [comment]
▶ Carnage - WDYW Feat. Lil Uzi Vert, A$AP Ferg, Rich The Kid by Dj Carnage
https://m.soundcloud.com/djcarnageofficial/carnage-wdyw-feat-asap-ferg-lil-uzi-rich-the-kid

**Comment by ericelliott** [comment]
I'm not feeling the pain point that this library solves. When I don't need React, I simply use template literals or direct DOM updates. For larger applications, I prefer the structure that React provides. If I felt perf issues, I'd probably try Inferno.js instead of Monkberry. Thanks for your suggestion. =)

**Comment by elfet** [comment]
Ok; no "classes are bad" mantra for today?

**Comment by ericelliott** [comment]
Haha, I use class-free React. ;)
