### ISSUE TITLE
Add rollup.js in Building

### ISSUE THREAD

**Issue by csbun** [ericelliott/essential-javascript-links#67]
[rollup.js](http://rollupjs.org/): the next-generation JavaScript module bundler

**Comment by ericelliott** [comment]
Both Browserify and Webpack are committed to features such as tree-shaking to shrink bundle sizes. The Rollup plugin/dev tool ecosystem is also just barely getting started. It's an interesting project, and usable for small projects, but I don't think it's ready for prime-time, yet.
