### ISSUE TITLE
add jlongster.com/Modularity

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/essential-javascript-links#7]
Great blogpost.

**Comment by hoichi** [comment]
It's http://jlongster.com/Modularity
I guess most linux-based servers are case-sensitive.

Maybe add a direct link to @substack's gist too? I think it's pretty useful for those who don't know much about Webpack or Browserify (like me) or haven't made up their minds yet.

**Comment by ericelliott** [comment]
Thanks. =)

**Comment by hoichi** [comment]
Thank _you_. If not for your list(s), I'd still be reading Flanagan's _Definitive Guide_ (which is now waiting for its time) instead of doing exercises in _Eloquent JS_ :)

**Comment by ericelliott** [comment]
This is done. I guess I forgot to close. =)
