### ISSUE TITLE
Lodash-FP version discontinued

### ISSUE THREAD

**Issue by dansumption** [ericelliott/essential-javascript-links#73]
I also noticed that the link to Lodash-FP points to an archive version, which contains the following in the readme:

"Discontinued

This package has been discontinued in favor of lodash/fp"

However, I did not submit a fix, as lodash/fp appears to link to within a codebase, with no readme, so I was not sure where best to link to.

**Comment by ericelliott** [comment]
Please PR, changing Lodash-FP to Lodash. =)

**Comment by ericelliott** [comment]
Fixed.

**Comment by dansumption** [comment]
Nice, thanks! That's what I _thought_ was the right solution, but I wasn't sure of myself.

I guess next time I'll just dive in with a PR :)

**Comment by ericelliott** [comment]
:+1:
