### ISSUE TITLE
Hashtags in README.md

### ISSUE THREAD

**Issue by abrarShariar** [ericelliott/essential-javascript-links#89]
The hashtags defining various categories currently appear as #code #video #exercises etc..
This is an excellent way to find categories that met your requirements.

In order to make it more noticeable and thus easier to navigate the tags can be made **bold** as **#code**  **#video** (as shown in [contributing.md](https://github.com/ericelliott/essential-javascript-links/blob/master/contributing.md) )

It might make the life of new visitors easier and the overall search more efficient.

**Comment by ericelliott** [comment]
👍
