### ISSUE TITLE
Can I take the full list and add it to my web site?

### ISSUE THREAD

**Issue by paaljoachim** [ericelliott/essential-javascript-links#91]
Hey

I run the web site http://easywebdesigntutorials.com/
I think it would be beneficial if I added the full list to a new post. Is this alright?
I will mention that I copied the full list from this Github repo and that I would advise people to check here for the newest update.

**Comment by nickmccurdy** [comment]
It's fine, [read the license](https://github.com/ericelliott/essential-javascript-links/blob/master/LICENSE). You just have to include the copyright notice and license (MIT).

**Comment by paaljoachim** [comment]
I added a link to this Github repo instead:
http://www.easywebdesigntutorials.com/javascript-js-resources/
