### ISSUE TITLE
immutable.js

### ISSUE THREAD

**Issue by twakjaco** [ericelliott/essential-javascript-links#99]
You have a link under the React section called "Immutable Data and React" which links to a video about immutable.js.  However, I didn't see a reference to it in the "Libraries" section and I wondered if that might be helpful to some people.  I personally believe that immutable.js one of the "best of the best" libraries which encourages good software engineering practices.  Do you agree?  Would you consider adding a link to immutable.js?

**Comment by ericelliott** [comment]
I agree. PR?
